// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv5NoGR3Pe8GsElcwqLgLB0AbiWGu9sKM',
    appId: '1:57787875381:android:328d50cda5b057a550f17c',
    messagingSenderId: '57787875381',
    projectId: 'my-notes-flutter-firebase-app',
    storageBucket: 'my-notes-flutter-firebase-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdvv1ZgpgJs7_j320EuGfR-mylP636bjk',
    appId: '1:57787875381:ios:45f64318311ed1f850f17c',
    messagingSenderId: '57787875381',
    projectId: 'my-notes-flutter-firebase-app',
    storageBucket: 'my-notes-flutter-firebase-app.appspot.com',
    iosClientId: '57787875381-srb1j3uu7u65l9mfl5njogdcb0vmd9d4.apps.googleusercontent.com',
    iosBundleId: 'io.thusharathiwanka.my-notes',
  );
}
